[book]
authors = ["Bhavik Patel"]
language = "en"
multilingual = false
src = "book-content"
title = "Saute & Simmer"

# MDBOOK: https://rust-lang.github.io/mdBook/guide/creating.html
[output.html]
no-section-label = true


[preprocessor.callouts] # https://crates.io/crates/mdbook-callouts


# cargo install mdbook 
# cargo install mdbook-callouts
# cargo install mdbook-tag
